### ISSUE TITLE
provide a mongodb dump for example

### ISSUE THREAD

**Issue by zodman** [lae/wagnaria#6]
like config.yaml.example but for mongo

**Comment by IanMitchell** [comment]
There should be an example on another git site - can't remember how I found it. Try looking for where his idol activities site is hosted?

**Comment by zodman** [comment]
wget "https://c.milkteafuzz.com/api/1/shows.json"
mongoimport --host localhost --db wagnaria --collection shows --file shows.json --jsonArray --drop
wget https://c.milkteafuzz.com/api/1/staff.json
mongoimport --host localhost --db wagnaria --collection staff  --file staff.json --jsonArray --drop
